categories:
- Sequence Analysis
description: A tool for automated alignment trimming
long_description: |
  trimAl is a tool for the automated removal of spurious sequences or poorly aligned regions from a multiple sequence alignment.
homepage_url: https://vicfero.github.io/trimal/
name: trimal
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/trimal
type: unrestricted
