name: groot
owner: iuc
description: GROOT is a tool to type Antibiotic Resistance Genes (ARGs) in metagenomic samples
long_description: |
  GROOT is a tool to type Antibiotic Resistance Genes (ARGs) in metagenomic samples (a.k.a. Resistome Profiling). 
  It combines variation graph representation of gene sets with an LSH indexing scheme to allow for fast classification of metagenomic reads. 
  Subsequent hierarchical local alignment of classified reads against graph traversals facilitates accurate reconstruction of full-length gene sequences using a simple scoring scheme.
categories:
- Sequence Analysis
homepage_url: https://github.com/will-rowe/groot
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/groot
type: unrestricted
